version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: taisuke
      POSTGRES_USER: taisuke
      POSTGRES_DB: taisuke
    ports:
      - 5433:5432
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
  todo-actix:
    build: .
    links:
      - postgres
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 8080
      PG.USER: taisuke
      PG.PASSWORD: taisuke
      PG.HOST: postgres
      PG.PORT: 5433
      PG.DBNAME: taisuke
      PG.POOL.MAX_SIZE: 30
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
    ports:
      - 8080:8080
